### ISSUE TITLE
Homepage console errors

### ISSUE THREAD

**Issue by yaseralnajjar** [coretabs-academy/website-v2#156]
![image.png](https://images.zenhubusercontent.com/5b204d094b5806bc2bd74bc9/081833b9-3772-4a68-9bbf-d743278041c1)

**Comment by LouayH** [comment]
Most of them caused by AD Blocker

**Comment by yaseralnajjar** [comment]
I ran opera in incognito mode (no plugins), and some errors are gone now... others are left

![image.png](https://images.zenhubusercontent.com/5b204d094b5806bc2bd74bc9/be1b1a16-9bfc-4328-bec7-b1157d158fb2)

**Comment by LouayH** [comment]
First One caused by vue-youtube plugin and I've tried to solve it, and I'm still working on it. This is only error I have on my console.

Last Two caused by a chrome-extension as you can see.
