### ISSUE TITLE
Optimize SPA docker image

### ISSUE THREAD

**Issue by yaseralnajjar** [coretabs-academy/website-v2#36]
### Current situation

All the dependencies are inside the docker SPA production image which makes the image over-sized.

### Candidates

1. nginx to serve the static files.
2. express with npm with just production files to serve the spa.
3. any other multi-step docker available solution.

**Comment by LouayH** [comment]
https://github.com/coretabs-academy/website-v2/commit/f9d1f8c22849219e0113febd330149d31238e0bd

copy ./static/                     ->  ./new-path/static/
copy ./express.js                ->  ./new-path/express.js
copy ./package.express.js  ->  ./new-path/package.json
